spring:
  application:
    name: kotlin-spring-demo
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
